### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by lhotamir** [kodi-czsk/plugin.video.ivysilani#25]
Při spouštění přehrávání vyskočí následující chyba:

> 14:49:06.454 T:2971661056   ERROR: [iVys<C3><AD>l<C3><A1>n<C3><AD> <E2><80><94> <C4><8C>esk<C3><A1> televize] ['Traceback (most recent call last):  File "/home/osmc/.kodi/addons/plugin.video.ivysilani/addon.py", line 491, in <module>
    playPlayable(playable, skip_auto, force_quality)
  File "/home/osmc/.kodi/addons/plugin.video.ivysilani/addon.py", line 304, in playPlayable
    url = autoSelectQuality(playable)
  File "/home/osmc/.kodi/addons/plugin.video.ivysilani/addon.py", line 238, in autoSelectQuality
    url = playable.url(setting_quality)
  File "/home/osmc/.kodi/addons/plugin.video.ivysilani/ivysilani.py", line 196, in url
    if urllib2.urlopen(url).getcode() == 200:
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    \'http\', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    \'_open\', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

Zkusil jsem upravit ivysilani.py:196 aby se certifikát neověřoval, dostal jsem se na výběr kvality a když jsem vybral, dál už se nic nedělo.

Je možné že jim prostě vypršela platnost certifikátu a není to chyba pluginu, ale to jsem z té chyby nezjistil.

**Comment by E000001** [comment]
plugin jede, zavírám.
