### ISSUE TITLE
Plugin přestal pracovat

### ISSUE THREAD

**Issue by pschonmann** [kodi-czsk/plugin.video.ivysilani#31]
```
2019-04-02 21:56:27.606 T:1164903280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: bad marshal data (unknown type code)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ivysilani/addon.py", line 20, in <module>
                                                import ivysilani
                                              File "/storage/.kodi/addons/plugin.video.ivysilani/ivysilani.py", line 14, in <module>
                                                import util
                                            ValueError: bad marshal data (unknown type code)
                                            -->End of Python script error report<--
2019-04-02 21:56:27.621 T:1148117872   ERROR: GetDirectory - Error getting plugin://plugin.video.ivysilani/
2019-04-02 21:56:27.623 T:1937743888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ivysilani/) failed```

**Comment by pschonmann** [comment]
Stále neopraveno :(

**Comment by jandurovec** [comment]
`bad marshal data (unknown type code)` ukazuje spíš na chybu ve zkompilovaném objektu než na chybu ve zdrojovém kódu. Zkuste smazat `*.pyo` soubory v adresáři s pluginem.

Viz https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data

Jakou verzi Kodi a na jakém OS používáte?

**Comment by pschonmann** [comment]
rm ~/.kodi/addons/plugin.video.ivysilani/*.pyo nepomohlo.

Používám Kodi 18.1 na Libreelec 9.0.1

**Comment by jandurovec** [comment]
Ta chyba je ale u importu modulu `util` ze `script.module.stream.resolver`. Smazal bych `util.pyo` v té závislosti.

**Comment by pschonmann** [comment]
Skvělé, tohle pomohlo.
